%% Plot all relevant joint variables
function plotJointPVA(q, qd, qdd, tSamples, T, beta)
    q = rad2deg(q);
    qd = rad2deg(qd);
    qdd = rad2deg(qdd);

    q1Color = '#000000';
    q2Color = '#A2142F';
    q3Color = '#0072BD';
    qd1Color = '#515684';
    qd2Color = '#D95319';
    qd3Color = '#4DBEEE';
    qdd1Color = '#EDB120';
    qdd2Color = '#7E2F8E';
    qdd3Color = '#77AC30';

    [L1, L2, L3, L4] = utils.getPhaseOffsets(beta);
    
    figure;
    t = tiledlayout(3,4,'TileSpacing','compact');
    t.XLabel.String = 'Period (s)';
    t.XLabel.FontSize = 14;
    t.XLabel.Interpreter = 'latex';

    nexttile;
    hold on;
    tq1 = plot(tSamples+T*L1(1),q(1,:),Color=q1Color);
    plot(tSamples+T*L1(1) - T,q(1,:),Color=q1Color);
    tq2 = plot(tSamples+T*L1(1),q(2,:),Color=q2Color);
    plot(tSamples+T*L1(1) - T,q(2,:),Color=q2Color);
    tq3 = plot(tSamples+T*L1(1),q(3,:),Color=q3Color);
    plot(tSamples+T*L1(1) - T,q(3,:),Color=q3Color);
    xlim([0 T]);
    ylim([-90 90]);
    title('Leg 1', 'Interpreter','latex')
    ylabel('$Deg$', 'Interpreter','latex');
    xticks([]);
    nexttile;
    hold on;
    plot(tSamples+T*L2(3),q(1,:),Color=q1Color);
    plot(tSamples+T*L2(3) - T,q(1,:),Color=q1Color);
    plot(tSamples+T*L2(3),q(2,:),Color=q2Color);
    plot(tSamples+T*L2(3) - T,q(2,:),Color=q2Color);
    plot(tSamples+T*L2(3),q(3,:),Color=q3Color);
    plot(tSamples+T*L2(3) - T,q(3,:),Color=q3Color);
    xlim([0 T]);
    ylim([-90 90]);
    title('Leg 2', 'Interpreter','latex')
    xticks([]);
    yticks([]);
    nexttile;
    hold on;
    plot(tSamples+T*L3(3),q(1,:),Color=q1Color);
    plot(tSamples+T*L3(3) - T,q(1,:),Color=q1Color);
    plot(tSamples+T*L3(3),q(2,:),Color=q2Color);
    plot(tSamples+T*L3(3) - T,q(2,:),Color=q2Color);
    plot(tSamples+T*L3(3),q(3,:),Color=q3Color);
    plot(tSamples+T*L3(3) - T,q(3,:),Color=q3Color);
    xlim([0 T]);
    ylim([-90 90]);
    title('Leg 3', 'Interpreter','latex')
    xticks([]);
    yticks([]);
    nexttile;
    hold on;
    plot(tSamples+T*L4(1),q(1,:),Color=q1Color);
    plot(tSamples+T*L4(1) - T,q(1,:),Color=q1Color);
    plot(tSamples+T*L4(1),q(2,:),Color=q2Color);
    plot(tSamples+T*L4(1) - T,q(2,:),Color=q2Color);
    plot(tSamples+T*L4(1),q(3,:),Color=q3Color);
    plot(tSamples+T*L4(1) - T,q(3,:),Color=q3Color);
    xlim([0 T]);
    ylim([-90 90]);
    title('Leg 4', 'Interpreter','latex')
    xticks([]);
    yticks([]);

    nexttile;
    hold on;
    tqd1 = plot(tSamples+T*L1(1),qd(1,:),Color=qd1Color);
    plot(tSamples+T*L1(1) - T,qd(1,:),Color=qd1Color);
    tqd2 = plot(tSamples+T*L1(1),qd(2,:),Color=qd2Color);
    plot(tSamples+T*L1(1) - T,qd(2,:),Color=qd2Color);
    tqd3 = plot(tSamples+T*L1(1),qd(3,:),Color=qd3Color);
    plot(tSamples+T*L1(1) - T,qd(3,:),Color=qd3Color);
    xlim([0 T]);
    ylim([-200 600]);
    ylabel('$Deg/Sec$', 'Interpreter','latex');
    xticks([]);
    nexttile;
    hold on;
    plot(tSamples+T*L2(3),qd(1,:),Color=qd1Color);
    plot(tSamples+T*L2(3) - T,qd(1,:),Color=qd1Color);
    plot(tSamples+T*L2(3),qd(2,:),Color=qd2Color);
    plot(tSamples+T*L2(3) - T,qd(2,:),Color=qd2Color);
    plot(tSamples+T*L2(3),qd(3,:),Color=qd3Color);
    plot(tSamples+T*L2(3) - T,qd(3,:),Color=qd3Color);
    xlim([0 T]);
    ylim([-200 600]);
    xticks([]);
    yticks([]);
    nexttile;
    hold on;
    plot(tSamples+T*L3(3),qd(1,:),Color=qd1Color);
    plot(tSamples+T*L3(3) - T,qd(1,:),Color=qd1Color);
    plot(tSamples+T*L3(3),qd(2,:),Color=qd2Color);
    plot(tSamples+T*L3(3) - T,qd(2,:),Color=qd2Color);
    plot(tSamples+T*L3(3),qd(3,:),Color=qd3Color);
    plot(tSamples+T*L3(3) - T,qd(3,:),Color=qd3Color);
    xlim([0 T]);
    ylim([-200 600]);
    xticks([]);
    yticks([]);
    nexttile;
    hold on;
    plot(tSamples+T*L4(1),qd(1,:),Color=qd1Color);
    plot(tSamples+T*L4(1) - T,qd(1,:),Color=qd1Color);
    plot(tSamples+T*L4(1),qd(2,:),Color=qd2Color);
    plot(tSamples+T*L4(1) - T,qd(2,:),Color=qd2Color);
    plot(tSamples+T*L4(1),qd(3,:),Color=qd3Color);
    plot(tSamples+T*L4(1) - T,qd(3,:),Color=qd3Color);
    xlim([0 T]);
    ylim([-200 600]);
    xticks([]);
    yticks([]);
    
    nexttile;
    hold on;
    tqdd1 = plot(tSamples+T*L1(1),qdd(1,:),Color=qdd1Color);
    plot(tSamples+T*L1(1) - T,qdd(1,:),Color=qdd1Color);
    tqdd2 = plot(tSamples+T*L1(1),qdd(2,:),Color=qdd2Color);
    plot(tSamples+T*L1(1) - T,qdd(2,:),Color=qdd2Color);
    tqdd3 = plot(tSamples+T*L1(1),qdd(3,:),Color=qdd3Color);
    plot(tSamples+T*L1(1) - T,qdd(3,:),Color=qdd3Color);
    xlim([0 T]);
    ylim([-4000 4000]);
    ylabel('$Deg/Sec^{2}$', 'Interpreter','latex');
    nexttile;
    hold on;
    plot(tSamples+T*L2(3),qdd(1,:),Color=qdd1Color);
    plot(tSamples+T*L2(3) - T,qdd(1,:),Color=qdd1Color);
    plot(tSamples+T*L2(3),qdd(2,:),Color=qdd2Color);
    plot(tSamples+T*L2(3) - T,qdd(2,:),Color=qdd2Color);
    plot(tSamples+T*L2(3),qdd(3,:),Color=qdd3Color);
    plot(tSamples+T*L2(3) - T,qdd(3,:),Color=qdd3Color);
    xlim([0 T]);
    ylim([-4000 4000]);
    yticks([]);
    nexttile;
    hold on;
    plot(tSamples+T*L3(3),qdd(1,:),Color=qdd1Color);
    plot(tSamples+T*L3(3) - T,qdd(1,:),Color=qdd1Color);
    plot(tSamples+T*L3(3),qdd(2,:),Color=qdd2Color);
    plot(tSamples+T*L3(3) - T,qdd(2,:),Color=qdd2Color);
    plot(tSamples+T*L3(3),qdd(3,:),Color=qdd3Color);
    plot(tSamples+T*L3(3) - T,qdd(3,:),Color=qdd3Color);
    xlim([0 T]);
    ylim([-4000 4000]);
    yticks([]);
    nexttile;
    hold on;
    plot(tSamples+T*L4(1),qdd(1,:),Color=qdd1Color);
    plot(tSamples+T*L4(1) - T,qdd(1,:),Color=qdd1Color);
    plot(tSamples+T*L4(1),qdd(2,:),Color=qdd2Color);
    plot(tSamples+T*L4(1) - T,qdd(2,:),Color=qdd2Color);
    plot(tSamples+T*L4(1),qdd(3,:),Color=qdd3Color);
    plot(tSamples+T*L4(1) - T,qdd(3,:),Color=qdd3Color);
    xlim([0 T]);
    ylim([-4000 4000]);
    yticks([]);

    lg = legend([tq1(1), tq2(1), tq3(1), tqd1(1), tqd2(1), tqd3(1), tqdd1(1), tqdd2(1), tqdd3(1)], '$q_{1}$','$q_{2}$','$q_{3}$','$\dot q_{1}$','$\dot q_{2}$','$\dot q_{3}$','$\ddot q_{1}$','$\ddot q_{2}$','$\ddot q_{3}$');
    lg.NumColumns = 3;
    set(lg,'Interpreter','latex');
    set(lg,'FontSize',12);
    lg.Layout.Tile = 'east';
    hold off;
end